### ISSUE TITLE
Error generating QRCode in memory

### ISSUE THREAD

**Issue by outdooracorn** [jmptbl/python-zint#7]
I'm using the exact same code as [Example 2](https://github.com/jmptbl/python-zint#example-2) but I'm getting the following error:

```
Traceback (most recent call last):
  File "****/playpit.py", line 38, in <module>
    bitmap = zint.bitmapbuf(symbol)
  File "****/.venv/lib/python3.8/site-packages/zint/zint.py", line 218, in bitmapbuf
    blen = z.contents.bitmap_width * z.contents.bitmap_height * 3
AttributeError: 'zint_symbol' object has no attribute 'bitmap_width'
```

Printing to file using [Example 1](https://github.com/jmptbl/python-zint#example-1) works fine.

python-zint version = 1.2 (latest on PyPI)
libzint.so version = 2.8.0
Python version = 3.8.3
OS = Manjaro

**Comment by jmptbl** [comment]
@outdooracorn python-zint 1.4 was just committed which I believe should solve the issue you found. It seems like Python's ctypes interface changed slightly after Python 2.7.
